### ISSUE TITLE
SelBlocks Global - improved SelBlocks for Selenium IDE

### ISSUE THREAD

**Issue by peter-kehl** [SeLite/SelBlocksGlobal#2]
@oraclemohammadi, @apodhajsky, @middreks, @bobiben, @patrick-hubert-adsk,

You've commented on an issue in SelBlocks (that loops don't work in WebDriver). I don't have a fix for that.

However, if you were interested in getting more value in Selenium IDE, use SelBlocks Global, and related components. See http://selite.github.io.

**Comment by peter-kehl** [comment]
Hi @tn801534,

You have used user-extensions.js of SelBlocks.

If you were interested in getting more value in Selenium IDE, use SelBlocks Global and SeLite. See http://selite.github.io.

**Comment by peter-kehl** [comment]
Hi Darren @73rhodes,

Thank you for Sideflow for Selenium IDE. 

Would you like to get more value out of Selenium IDE? See @SeLite. Its documentation is at http://selite.github.io.

**Comment by peter-kehl** [comment]
@SeLite @peter-kehl test

**Comment by peter-kehl** [comment]
Hi Stephen @cressie176,

Thank you for Natural Language Extensions for Selenium IDE.

Would you like to get more value out of Selenium IDE? Use @SeLite. See its documentation  at http://selite.github.io.

**Comment by peter-kehl** [comment]
Hi @allmyitjason,

Thank you for Selenium IDE Codeception formatter.

Would you like to get more value out of Selenium IDE? Use @SeLite. See its documentation at http://selite.github.io.

**Comment by peter-kehl** [comment]
Hi Dennis @denschu,

Thank you for Selenium IDE Extension: Clipboard Format for Robotframework.

Would you like to get more value out of Selenium IDE? Use @SeLite. See its documentation at http://selite.github.io.

**Comment by peter-kehl** [comment]
Hi Abishek @abhijain2618,

Thank you for CSV file reader plugin for Selenium IDE.

Would you like to get more value out of Selenium IDE? Use @SeLite. See its documentation at http://selite.github.io.

**Comment by peter-kehl** [comment]
Hi Shane @sbarbett,

You've created Neustar script recorder for Selenium IDE.

Would you like to get more value out of Selenium IDE outside of script.wpm.neustar.biz? Use @SeLite. See its documentation at http://selite.github.io.

**Comment by peter-kehl** [comment]
Hi @cysam,

You've contributed to Neustar script recorder for Selenium IDE.

Would you like to get more value out of Selenium IDE outside of script.wpm.neustar.biz? Use @SeLite. See its documentation at http://selite.github.io.

**Comment by peter-kehl** [comment]
Hi Hélio @HelioGuilherme66,

Thank you for Robot Framework.

If you were interested in running Selenium IDE (other than exporting to Robot Framework), you can get more value with  @SeLite. See its documentation at http://selite.github.io.

**Comment by peter-kehl** [comment]
Hi Bach @NeverSmileK57CLC,

Thank you for Robot Framework formatter for Selenium IDE.

If you were interested in running Selenium IDE (other than exporting to Robot Framework), you can get more value with @SeLite. See its documentation at http://selite.github.io.

**Comment by 73rhodes** [comment]
Please, please, please stop CC'ing me to this entire list.
