### ISSUE TITLE
Unexpected errors after some time. Msg: TypeError: pagesets[i].getUISpecifierStringStubs is not a function

### ISSUE THREAD

**Issue by SlitEye** [SeLite/SelBlocksGlobal#6]
## Description -
There are unexpected errors after some time using Selenium IDE with SeLite addons, specially SelBlocks Global:
**"Msg: TypeError: pagesets[i].getUISpecifierStringStubs is not a function"**

The errors  are appeared the first time after I installed the SeLite addons.

## Meta -
**OS:**  Windows 7 Enterprise SP1 x64
**Selenium Version:**  Selenium IDE for Firefox v2.9.1.1-signed
**Browser:**  Firefox for Windows systems
**Browser Version:**  
from Firefox 49 up to Firefox 50.0.2 (32-bit) and also Firefox 50.0.2 (64-bit)
**Language (OS | Browser: Firefox | Selenium IDE addon):** english | german | german

**Currently installed firefox, Selenium IDE and SeLite addons:**
- Selenium IDE: v2.9.1.1-signed
- Highlight Elements (Selenium IDE): v1.22.1-signed.1-signed
- File Logging (Selenium IDE): v3.0.1-signed
- Log Search Bar (Selenium IDE): v1.22.1-signed.1-signed
- Stored Variables (Selenium IDE): v2.0.1-signed.1-signed
- Test Results (Selenium IDE): v2.0.1-signed.1-signed
- SeLite
-- SeLite AutoCheck: v0.12
-- SeLite Clipboard And Indent: v0.23
-- SeLite Commands: v0.98
-- SeLite DB Objects: v0.91
-- SeLite Exit Confirmation Checker: v0.14
-- SeLite Miscellaneous: v1.09
-- SeLite SelBlocks Global: v2.68
-- SeLite Settings: v0.65
-- SeLite SQLite Connection Manager: v0.77
-- SeLite TestCase Debug Context: v0.80
-- SeLite Bootstrap: v0.96
-- SeLite Extension Sequencer: v0.53
-- SeLite Run All Favorites: v0.15

**Installed addons before / in the past:**
- Selenium IDE: v2.9.1.1-signed
- Highlight Elements (Selenium IDE): v1.22.1-signed.1-signed
- File Logging (Selenium IDE): v3.0.1-signed
- Log Search Bar (Selenium IDE): v1.22.1-signed.1-signed
- Stored Variables (Selenium IDE): v2.0.1-signed.1-signed
- Test Results (Selenium IDE): v2.0.1-signed.1-signed
- Page Coverage (Selenium IDE): v1.15.1-signed.1-signed
- Screenshot on Fail (Selenium IDE): v1.14.1-signed.1-signed
- Selenium IDE: Selenium 2 Excel Converter: v1.0.1.1-signed.1-signed
- Selenium Wiki Formatter: v1.0.1-signed.1-signed
- Separated Values Formatter (Selenium IDE): v1.0.0.1-signed.1-signed
- WebDriver Backed Formatters: v1.0.4.1-signed.1-signed
- SeLite
-- SeLite AutoCheck: v0.12
-- SeLite Clipboard And Indent: v0.23
-- SeLite Commands: v0.98
-- SeLite DB Objects: v0.91
-- SeLite Exit Confirmation Checker: v0.14
-- SeLite Miscellaneous: v1.09
-- SeLite SelBlocks Global: v2.68
-- SeLite Settings: v0.65
-- SeLite SQLite Connection Manager: v0.77
-- SeLite TestCase Debug Context: v0.80
-- SeLite Bootstrap: v0.96
-- SeLite Extension Sequencer: v0.53
-- SeLite Run All Favorites: v0.15

I don't know really how I can reproduce or provoke the described errors. It seems to me, that the errors appears faster if I have execute my own JS injections in my test suites. But, my JS injections are only default ECMA JS:
[ETC_Tenant_StdLib_Core.zip](https://github.com/SeleniumHQ/selenium/files/626985/ETC_Tenant_StdLib_Core.zip)

Because these issues apears very often after installing of the SeLite addons, I have deinstalled / removed the SeLite addons with a rollback to the old "SelBlocks" (not SelBlocks Global). 
There are also related tickets of me at other Selenium IDE / addons projects, see: 
https://github.com/SeleniumHQ/selenium/issues/3194
https://github.com/refactoror/SelBlocks/issues/31

Please start the investigation and fix the errors, because we want SelBlocks Global and not SelBlocks.

Best regards, 

Kevin Marco Erler
QA at INTERSHOP Communications AG - FullService

**Comment by peter-kehl** [comment]
Not specific to SeLite. See https://github.com/SeleniumHQ/selenium/issues/3194.
