### ISSUE TITLE
Error: $$.fn.XmlReader is not a constructor

### ISSUE THREAD

**Issue by MacTheFork** [SeLite/SelBlocksGlobal#7]
This is the same issue recorded as "forXml: Unexpected Exception: Error: $$.fn.XmlReader is not a constructor #14" opened for SeLite at https://github.com/SeLite/SeLite/issues/14
I've opened an issue here as this is where the defect actually is

A suggested fix for this is at selblocks.js line 1711:
`loop.xmlReader = new $$.fn.XmlReader();`
should be replaced with 
`loop.xmlReader = new XmlReader();`

**Comment by peter-kehl** [comment]
Thanks @MacTheFork and Jarmoir Obr @mirao.

Fixed. Deployed (pending Mozilla's review).
