### ISSUE TITLE
Error: $$.fn.JSONReader is not a constructor

### ISSUE THREAD

**Issue by MacTheFork** [SeLite/SelBlocksGlobal#8]
At the end of SeLite issue "forXml: Unexpected Exception: Error: $$.fn.XmlReader is not a constructor #14" opened at SeLite/SeLite#14, it is stated "The same issue happens with forJson"
I've opened a separate issue here for this  as this is where the defect actually is

A suggested fix is  in selblocks.js at line 1689
`loop.jsonReader = new $$.fn.JSONReader();`
should be 
`loop.jsonReader = new JSONReader();`

**Comment by peter-kehl** [comment]
Thanks @MacTheFork and Jarmoir Obr @mirao.

Fixed. Deployed (pending Mozilla's review).
