### ISSUE TITLE
ReferenceError: SeLiteSettings is not defined

### ISSUE THREAD

**Issue by AnswerWas42** [SeLite/SelBlocksGlobal#9]
Hi,

     When I start Selenium IDE then run the first test case, I get this message.   Once I dismiss it, everything appears to be working just fine, I can run test cases and test suites and don't see this error, and everything appears to be working just fine.  here is the error:

There was an unexpected error. Msg: ReferenceError: SeLiteSettings is not defined
Url: chrome://selite-selblocks-global/content/extensions/selblocks.js?1501599893388, line: 2540, column: 13
@chrome://selite-selblocks-global/content/extensions/selblocks.js?1501599893388:2540:13

If I uninstall all the SeLite components and add one at a time in the order listed below and test each incremental new add-on, the error only happens once the selblocks-global add-on is added.

I'm using Selenum 2.9.1 on Firefox 54.0.1 32 bit, Windows 7 64bit, with these SeLite components:
SeLite Extension Sequencer 0.53
SeLite Miscellaneous 1.09
SeLite TestCase Debug Context 0.81
eLite SelBlocks Global 2.70

**Comment by peter-kehl** [comment]
Yes, my bug. Fix is a work in progress.

Additionally, I'm having a problem to run Selenium IDE at all. What exact version of Selenium IDE do you have, and where from? Is it  2.9.1.1-signed from https://addons.mozilla.org/en-US/firefox/addon/selenium-ide/?

**Comment by AnswerWas42** [comment]
Thanks for the quick reply!     Selenium IDE is working for me, it's running tests right now.
Interesting, if I use the Help->Submit Diagnostic Information command in the Selenium IDE it states:
    "SeleniumIDE": { 
      "version": "2.9.1", 
      "sidebar": false     }
But the Add-On manager in Firefox says 2.9.1.1-signed, last updated May 3, 2017.   Retrieved from
https://addons.mozilla.org/en-US/firefox/addon/selenium-ide/   

I don't have many other plugins or add-ons installed, trying to keep Firefox clean for Selenium.

**Comment by peter-kehl** [comment]
Fix packaged and published: https://addons.mozilla.org/en-US/firefox/addon/selite-selblocks-global/

**Comment by AnswerWas42** [comment]
Hi Peter - sorry this reply got stuck in my drafts folder - not sure why, it's pretty irrelevant now:
Hi Peter,
Thanks for the quick reply!   
Interesting, if I use the Help->Submit Diagnostic Information command in the Selenium IDE it states:
    "SeleniumIDE": {
      "version": "2.9.1",
      "sidebar": false
    }

But the Add-On manager in Firefox says 2.9.1.1-signed, last updated May 3, 2017.   Retrieved from Selenium IDE

| 
| 
| 
| $$0 |  |

 |

 |
| 
|  | 
Selenium IDE

Selenium IDE is an integrated development environment for Selenium tests. It is implemented as a Firefox extensi...
 |

 |

 |





On Wednesday, August 2, 2017, 7:19:37 AM CDT, Peter Kehl <notifications@github.com> wrote:


Yes, my bug. Fix is a work in progress.

Additionally, I'm having a problem to run Selenium IDE at all. What exact version of Selenium IDE do you have, and where from? Is it 2.9.1.1-signed from https://addons.mozilla.org/en-US/firefox/addon/selenium-ide/?

**Comment by AnswerWas42** [comment]
Got it!  The message is no longer appearing, thank you!!

On Wednesday, August 9, 2017, 2:47:06 AM CDT, Peter Kehl <notifications@github.com> wrote:


Fix packaged and published: https://addons.mozilla.org/en-US/firefox/addon/selite-selblocks-global/

**Comment by peter-kehl** [comment]
@AnswerWas42 
SeLite and Selenium IDE needs a community. Otherwise it will die with new Firefox. Would you like to support it - morally? Email me, please.

**Comment by AnswerWas42** [comment]
Hi Peter,
    I learned of this late wednesday, when I couldn't load test cases in Selenium IDE and thought I just needed to reboot.  Wow, what are the FireFox people thinking?   An update with no warning that would break and invalidate EVERY add-on that I have?   Yikes. 
    The Selenium IDE is a great tool and does a spectacular job of making testing and automation available to everyone, not just people that can afford a 4-figure testing tool.   I would love to see this environment continue on, but do worry that it will be a major committment to catch up to the new requirements for add-ons in Firefox.
     So yes, you have my moral support.  I was curious as to what your stake in the SeLite components is and whether or not the upgrade is viable.   Have you had a chance to surmise the effort in upgrading the components you have created?
Regards,
Don

On Wednesday, August 16, 2017, 11:07:18 PM CDT, Peter Kehl <notifications@github.com> wrote:


@AnswerWas42
SeLite and Selenium IDE needs a community. Otherwise it will die with new Firefox. Would you like to support it - morally? Email me, please.

**Comment by peter-kehl** [comment]
Hi Don,

Could you email me direct, please. Also, would you connect with me on Facebook and LinkedIn. That way we can reach out more.

peter.kehl at gmail
